#ifndef CMD_TASKTEST_H
#define CMD_TASKTEST_H

#include <stdbool.h>
#include <stdint.h>

#define TASKTEST_TRANSPORT_PAYLOAD_MAX 96u

typedef enum
{
    TASKTEST_TRANSPORT_TEST_CRC_KNOWN_VECTOR = 0,
    TASKTEST_TRANSPORT_TEST_CANONICAL_JOIN,
    TASKTEST_TRANSPORT_TEST_SEQUENCE_INITIAL,
    TASKTEST_TRANSPORT_TEST_SEQUENCE_GAP,
    TASKTEST_TRANSPORT_TEST_SEQUENCE_STALE,
    TASKTEST_TRANSPORT_TEST_REPLAY_SAME,
    TASKTEST_TRANSPORT_TEST_REPLAY_MISMATCH,
    TASKTEST_TRANSPORT_TEST_RECURSIVE,
    TASKTEST_TRANSPORT_TEST_MAX_FRAME,
    TASKTEST_TRANSPORT_TEST_HARNESS_FIT,
    TASKTEST_TRANSPORT_TEST_HARNESS_LINE_FENCED,
    TASKTEST_TRANSPORT_TEST_HARNESS_END_MAX,
    TASKTEST_TRANSPORT_TEST_HARNESS_REJECT_MAX,
    TASKTEST_TRANSPORT_TEST_HARNESS_STATUS_MAX,
    TASKTEST_TRANSPORT_TEST_PS_LOOP_BOUNDS,
    TASKTEST_TRANSPORT_TEST_PS_LOOP_RECORD_FIT
} tasktest_transport_test_id_t;

int cmd_tasktest(int argc, char **argv);

#ifdef HOBBYOS_SELFTEST
uint32_t tasktest_transport_crc32(const char *payload, uint32_t length);
bool tasktest_transport_selftest_case(tasktest_transport_test_id_t test);
#endif

#endif
