#include "cmd_killtest.h"
#include "../../core/scheduler.h"
#include "../../core/semaphore.h"
#include "../../core/clock.h"
#include "../../core/task_metrics.h"
#include "../../drivers/timer.h"
#include "../../drivers/serial.h"
#include "../../memory/heap.h"
#include "../../libc/string.h"
#include "../../libc/memory.h"

typedef enum { KW_READY, KW_RUNNING, KW_SLEEPING, KW_BLOCKED, KW_GATED, KW_NORMAL, KW_NONKILL, KW_TIMEOUT } worker_mode_t;
typedef struct killtest_result {
    volatile uint8_t started, body_started, finished, cleanup_seen, release, cleanup_entered, cleanup_release, self_request, request_done;
    volatile uint32_t cleanup_count;
    volatile uint64_t checkpoints;
    task_id_t task_id;
    task_exit_reason_t exit_reason;
    task_wait_result_t wait_result;
    task_kill_result_t first_result, second_result, third_result;
    uint64_t kill_requested_ns;
    uint64_t cancellation_points;
    uint32_t sleep_ms;
    task_snapshot_t observed;
    semaphore_t sem;
} killtest_result_t;
typedef struct killtest_worker_ctx { killtest_result_t *result; worker_mode_t mode; uint8_t cleanup_wait; } killtest_worker_ctx_t;

static task_snapshot_t g_kt_page[64]; static task_id_t g_kt_ids[32];
static killtest_result_t *g_ui_no,*g_ui_free,*g_ui_pend,*g_ui_exit,*g_ui_zomb; static task_id_t g_ui_prot;
static volatile uint8_t g_cli_telemetry, g_ui_telemetry;
static volatile uint64_t g_contexts_live, g_wrong_reason, g_accepted_normal, g_worker_timeouts, g_quarantined_contexts;
static inline void kt_store_u8(volatile uint8_t*p,uint8_t v){__atomic_store_n(p,v,__ATOMIC_RELEASE);}
static inline uint8_t kt_load_u8(const volatile uint8_t*p){return __atomic_load_n(p,__ATOMIC_ACQUIRE);}
static inline void kt_store_u64(volatile uint64_t*p,uint64_t v){__atomic_store_n(p,v,__ATOMIC_RELEASE);}
static inline uint64_t kt_load_u64(const volatile uint64_t*p){return __atomic_load_n(p,__ATOMIC_ACQUIRE);}
static inline uint64_t kt_inc_u64(volatile uint64_t*p){return __atomic_add_fetch(p,1,__ATOMIC_RELAXED);}
static inline uint64_t kt_dec_u64(volatile uint64_t*p){return __atomic_sub_fetch(p,1,__ATOMIC_RELAXED);}
int killtest_cli_telemetry_enabled(void){return kt_load_u8(&g_cli_telemetry);}
int killtest_ui_telemetry_enabled(void){return kt_load_u8(&g_ui_telemetry);}
static void print_u64(uint64_t v){char b[21];uint32_t n=0;do{b[n++]=(char)('0'+v%10);v/=10;}while(v);while(n)serial_putc_all(b[--n]);}
static int emit(const char*n,bool ok){serial_write_all("[KILLTEST][");serial_write_all(n);serial_write_all(ok?"] PASS\n":"] FAIL\n");return ok?0:1;}
static bool wait_u8(volatile uint8_t *p,uint32_t ms){for(uint32_t i=0;i<ms;i++){if(kt_load_u8(p))return true;timer_sleep(1);}kt_inc_u64(&g_worker_timeouts);return false;}
static bool snapshot_id(task_id_t id,task_snapshot_t*out){task_snapshot_t local;return scheduler_snapshot_task_by_id(id,out?out:&local);}
static bool scan_pending_all(uint64_t now,uint64_t*out){for(uint32_t retry=0;retry<4;retry++){uint32_t off=0;uint64_t gen=0,pending=0;bool restart=false;for(;;){task_snapshot_t *s=g_kt_page;task_snapshot_result_t r=scheduler_snapshot_tasks(s,32,off);if(!off)gen=r.registry_generation;else if(r.registry_generation!=gen){restart=true;break;}for(uint32_t i=0;i<r.written;i++)if(s[i].kill_pending&&!s[i].exit_started&&s[i].kill_requested_ns&&now>s[i].kill_requested_ns+30000000000ULL)pending++;off+=r.written;if(!r.truncated){*out=pending;return true;}if(!r.written){restart=true;break;}}if(!restart)break;}return false;}
static bool wait_state(task_id_t id,task_state_t state,task_snapshot_t*out,uint32_t ms){for(uint32_t i=0;i<ms;i++){task_snapshot_t s;if(snapshot_id(id,&s)&&s.state==state){if(out)*out=s;return true;}timer_sleep(1);}return false;}
static bool wait_gone(task_id_t id,uint32_t ms){for(uint32_t i=0;i<ms;i++){if(!snapshot_id(id,NULL))return true;scheduler_reap_zombies(0);timer_sleep(1);}return false;}

static void worker_cleanup(void *arg){killtest_worker_ctx_t*c=arg;killtest_result_t*r=c->result;kt_store_u8(&r->cleanup_entered,1);if(c->cleanup_wait){
#ifndef HOBBYOS_KILL_NEGATIVE_ACCEPT_EXITING
timer_sleep(5);
#endif
while(!kt_load_u8(&r->cleanup_release))schedule_voluntary();}r->exit_reason=get_current_task()->exit_reason;__atomic_add_fetch(&r->cleanup_count,1,__ATOMIC_RELAXED);kt_store_u8(&r->finished,1);kt_store_u8(&r->cleanup_seen,1);kt_dec_u64(&g_contexts_live);kfree(c);}
static void test_worker(void *arg){killtest_worker_ctx_t*c=arg;killtest_result_t*r=c->result;
    if(c->mode==KW_READY){task_cancel_point();kt_store_u8(&r->started,1);kt_store_u8(&r->body_started,1);while(!kt_load_u8(&r->release))schedule_voluntary();return;}
    kt_store_u8(&r->started,1);kt_store_u8(&r->body_started,1);
    if((c->mode==KW_RUNNING||c->mode==KW_GATED||c->mode==KW_NONKILL)&&!kt_load_u8(&r->self_request)&&!kt_load_u8(&r->release))while(!kt_load_u8(&r->self_request)&&!kt_load_u8(&r->release))schedule_voluntary();
    if(kt_load_u8(&r->self_request)){scheduler_test_request_kill_when(r->task_id,TASK_TEST_MATCH_RUNNING_ON_CPU,&r->first_result,&r->observed);if(c->mode==KW_GATED){r->second_result=scheduler_request_kill(r->task_id);r->third_result=scheduler_request_kill(r->task_id);}kt_store_u8(&r->request_done,1);}
    if(c->mode==KW_SLEEPING){r->wait_result=timer_sleep_interruptible(60000);if(r->wait_result==TASK_WAIT_RESULT_CANCELLED)task_cancel_point();return;}
    if(c->mode==KW_BLOCKED){r->wait_result=sem_wait_interruptible(&r->sem);if(r->wait_result==TASK_WAIT_RESULT_CANCELLED)task_cancel_point();return;}
    if(c->mode==KW_TIMEOUT){r->wait_result=timer_sleep_interruptible(r->sleep_ms);if(r->wait_result==TASK_WAIT_RESULT_CANCELLED)task_cancel_point();task_cancel_point();return;}
    if(c->mode==KW_NORMAL)return;
    while(!kt_load_u8(&r->release)){if(c->mode==KW_RUNNING){kt_inc_u64(&r->checkpoints);task_cancel_point();}else schedule_voluntary();}
    if(c->mode==KW_GATED)task_cancel_point();
}
static killtest_result_t *create_case(worker_mode_t mode,uint32_t flags,uint8_t cleanup_wait,task_handle_t *out_handle){killtest_result_t*r=kmalloc(sizeof(*r));killtest_worker_ctx_t*c=kmalloc(sizeof(*c));if(!r||!c){if(r)kfree(r);if(c)kfree(c);return NULL;}memset(r,0,sizeof(*r));sem_init(&r->sem,0);c->result=r;c->mode=mode;c->cleanup_wait=cleanup_wait;r->sleep_ms=4;task_create_options_t o={.name="killtest-worker",.task_class=TASK_CLASS_NORMAL,.flags=flags,.cleanup_fn=worker_cleanup,.cleanup_ctx=c};scheduler_test_hold_reap_next_creation();kt_inc_u64(&g_contexts_live);task_handle_t h;if(!thread_create_ex_handle(test_worker,c,&o,&h)){scheduler_test_cancel_hold_reap_next_creation();kt_dec_u64(&g_contexts_live);kfree(c);kfree(r);return NULL;}kt_store_u64((volatile uint64_t*)&r->task_id,h.id);if(out_handle)*out_handle=h;return r;}
static bool finish_case(killtest_result_t*r,task_exit_reason_t reason){bool cleanup=wait_u8(&r->cleanup_seen,5000);bool finished=kt_load_u8(&r->finished);task_snapshot_t z;bool zombie=wait_state(r->task_id,TASK_ZOMBIE,&z,cleanup?5000:1);if(!cleanup||!finished||!zombie){kt_store_u8(&r->release,1);kt_store_u8(&r->cleanup_release,1);(void)scheduler_request_kill(r->task_id);cleanup=wait_u8(&r->cleanup_seen,1000);finished=kt_load_u8(&r->finished);zombie=wait_state(r->task_id,TASK_ZOMBIE,&z,1000);}bool lifetime=cleanup&&finished&&zombie;bool ok=lifetime&&__atomic_load_n(&r->cleanup_count,__ATOMIC_ACQUIRE)==1&&r->exit_reason==reason&&z.cleanup_done;if(cleanup&&r->exit_reason!=reason)kt_inc_u64(&g_wrong_reason);scheduler_test_hold_reap(r->task_id,false);if(!lifetime){kt_inc_u64(&g_quarantined_contexts);return false;}scheduler_reap_zombies(0);bool gone=wait_gone(r->task_id,1000);if(!gone){kt_inc_u64(&g_quarantined_contexts);return false;}kfree(r);return ok;}
static task_test_request_status_t request_when(killtest_result_t*r,task_test_match_t m,task_kill_result_t*out,uint32_t ms){for(uint32_t i=0;i<ms;i++){task_test_request_status_t s=scheduler_test_request_kill_when(r->task_id,m,out,&r->observed);if(s!=TASK_TEST_REQUEST_NOT_READY)return s;schedule_voluntary();}return TASK_TEST_REQUEST_NOT_READY;}

static int test_ready(void){for(uint32_t a=1;a<=64;a++){scheduler_test_hold_next_ready_creation();killtest_result_t*r=create_case(KW_READY,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit("READY",false);scheduler_test_hold_reap(r->task_id,true);task_kill_result_t kr;task_test_request_status_t s=scheduler_test_request_kill_when(r->task_id,TASK_TEST_MATCH_READY_OFF_CPU,&kr,&r->observed);if(s==TASK_TEST_REQUEST_APPLIED){bool before=!kt_load_u8(&r->started)&&!kt_load_u8(&r->body_started)&&r->observed.state==TASK_READY&&!r->observed.on_cpu;bool done=finish_case(r,TASK_EXIT_KILLED);serial_write_all("[KILLTEST][READY] ");serial_write_all(before&&kr==TASK_KILL_ACCEPTED&&done?"PASS":"FAIL");serial_write_all(" attempts=");print_u64(a);serial_write_all(" observed=READY body_started=");print_u64(before?0:1);serial_write_all("\n");return before&&kr==TASK_KILL_ACCEPTED&&done?0:1;}kt_store_u8(&r->release,1);finish_case(r,TASK_EXIT_NORMAL);}return emit("READY",false);}
static int test_running(void){killtest_result_t*r=create_case(KW_RUNNING,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit("RUNNING",false);scheduler_test_hold_reap(r->task_id,true);kt_store_u8(&r->self_request,1);bool applied=wait_u8(&r->request_done,5000)&&r->first_result==TASK_KILL_ACCEPTED&&r->observed.state==TASK_RUNNING&&r->observed.on_cpu;uint32_t cpu=r->observed.current_cpu_slot;uint64_t cp=r->checkpoints;bool done=finish_case(r,TASK_EXIT_KILLED);bool ok=applied&&done;serial_write_all("[KILLTEST][RUNNING] ");serial_write_all(ok?"PASS":"FAIL");serial_write_all(" cpu=");print_u64(cpu);serial_write_all(" checkpoints=");print_u64(cp);serial_write_all("\n");return ok?0:1;}
static int test_wait(worker_mode_t mode,task_test_match_t match,const char*name){killtest_result_t*r=create_case(mode,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit(name,false);scheduler_test_hold_reap(r->task_id,true);task_kill_result_t kr;bool applied=request_when(r,match,&kr,5000)==TASK_TEST_REQUEST_APPLIED;bool observed=(mode==KW_SLEEPING?r->observed.wait_kind==TASK_WAIT_TIMER_SLEEP:r->observed.wait_kind==TASK_WAIT_SEMAPHORE)&&r->observed.wait_active;bool done=finish_case(r,TASK_EXIT_KILLED);return emit(name,applied&&observed&&kr==TASK_KILL_ACCEPTED&&done);}
static int test_duplicate(void){killtest_result_t*r=create_case(KW_GATED,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit("DUPLICATE",false);scheduler_test_hold_reap(r->task_id,true);kt_store_u8(&r->self_request,1);bool applied=wait_u8(&r->request_done,5000);task_snapshot_t s;snapshot_id(r->task_id,&s);bool stable=s.kill_requested_ns==r->observed.kill_requested_ns&&s.kill_request_count==1;bool results=r->first_result==TASK_KILL_ACCEPTED&&r->second_result==TASK_KILL_ALREADY_PENDING&&r->third_result==TASK_KILL_ALREADY_PENDING;kt_store_u8(&r->release,1);bool done=finish_case(r,TASK_EXIT_KILLED);return emit("DUPLICATE",applied&&results&&stable&&done);}
static int test_protected(void){task_snapshot_t *s=g_kt_page;task_snapshot_result_t n=scheduler_snapshot_tasks(s,64,0);task_id_t idle=0,critical=0;for(uint32_t i=0;i<n.written;i++){if(s[i].is_idle&&!idle)idle=s[i].id;if((s[i].flags&TASK_FLAG_KILL_PROTECTED)&&!s[i].is_idle&&!critical)critical=s[i].id;}task_kill_result_t a=scheduler_request_kill(idle),b=scheduler_request_kill(critical);task_handle_t h;killtest_result_t*r=create_case(KW_NONKILL,TASK_FLAG_SYSTEM|TASK_FLAG_KILL_PROTECTED,0,&h);if(!r)return emit("PROTECTED",false);scheduler_set_task_name_by_id(h.id,"ordinary-name");task_kill_result_t c=scheduler_request_kill(r->task_id);kt_store_u8(&r->release,1);bool done=finish_case(r,TASK_EXIT_NORMAL);return emit("PROTECTED",idle&&critical&&a==TASK_KILL_ERR_PROTECTED&&b==TASK_KILL_ERR_PROTECTED&&c==TASK_KILL_ERR_PROTECTED&&done);}
static int test_nonkill(void){killtest_result_t*r=create_case(KW_NONKILL,TASK_FLAG_SYSTEM,0,NULL);if(!r)return emit("NONKILLABLE",false);kt_store_u8(&r->self_request,1);bool applied=wait_u8(&r->request_done,5000);task_kill_result_t kr=r->first_result;
#ifdef HOBBYOS_KILL_NEGATIVE_IGNORE_KILLABLE
bool detected=applied&&kr==TASK_KILL_ACCEPTED&&!wait_u8(&r->cleanup_seen,100);if(detected)serial_write_all("[KILLTEST][NEGATIVE] NONKILLABLE_ACCEPTANCE_DETECTED\n");kt_store_u8(&r->release,1);finish_case(r,TASK_EXIT_NORMAL);return detected?0:1;
#else
bool untouched=r->observed.kill_requested_ns==0&&r->observed.kill_request_count==0&&!r->observed.kill_pending;kt_store_u8(&r->release,1);bool done=finish_case(r,TASK_EXIT_NORMAL);return emit("NONKILLABLE",applied&&kr==TASK_KILL_ERR_NOT_KILLABLE&&untouched&&done);
#endif
}
static int test_rename(void){task_handle_t h;killtest_result_t*r=create_case(KW_GATED,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,&h);if(!r)return emit("RENAME",false);scheduler_test_hold_reap(r->task_id,true);scheduler_set_task_name_by_id(h.id,"reaper");kt_store_u8(&r->self_request,1);bool applied=wait_u8(&r->request_done,5000);bool accepted=r->first_result==TASK_KILL_ACCEPTED;kt_store_u8(&r->release,1);bool done=finish_case(r,TASK_EXIT_KILLED);return emit("RENAME",applied&&accepted&&done);}
static int test_normal(void){killtest_result_t*r=create_case(KW_NORMAL,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit("NORMAL",false);scheduler_test_hold_reap(r->task_id,true);return emit("NORMAL",finish_case(r,TASK_EXIT_NORMAL));}
static int test_zombie(void){killtest_result_t*r=create_case(KW_GATED,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit("ZOMBIE",false);scheduler_test_hold_reap(r->task_id,true);kt_store_u8(&r->release,1);if(!wait_state(r->task_id,TASK_ZOMBIE,NULL,5000)){kt_store_u8(&r->release,1);finish_case(r,TASK_EXIT_NORMAL);return emit("ZOMBIE",false);}task_kill_result_t kr;task_snapshot_t o;bool applied=scheduler_test_request_kill_when(r->task_id,TASK_TEST_MATCH_ZOMBIE,&kr,&o)==TASK_TEST_REQUEST_APPLIED;bool done=finish_case(r,TASK_EXIT_NORMAL);return emit("ZOMBIE",applied&&kr==TASK_KILL_ALREADY_ZOMBIE&&!o.kill_pending&&done);}
static int test_exiting(bool killed){killtest_result_t*r=create_case(killed?KW_RUNNING:KW_NORMAL,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,1,NULL);if(!r)return emit(killed?"EXITING_KILLED":"EXITING_NORMAL",false);scheduler_test_hold_reap(r->task_id,true);task_kill_result_t first=TASK_KILL_ERR_INVALID;if(killed){kt_store_u8(&r->self_request,1);if(!wait_u8(&r->request_done,5000)||(first=r->first_result)!=TASK_KILL_ACCEPTED){kt_store_u8(&r->cleanup_release,1);finish_case(r,TASK_EXIT_NORMAL);return emit("EXITING_KILLED",false);}}if(!wait_u8(&r->cleanup_entered,5000)){kt_store_u8(&r->cleanup_release,1);finish_case(r,killed?TASK_EXIT_KILLED:TASK_EXIT_NORMAL);return emit(killed?"EXITING_KILLED":"EXITING_NORMAL",false);}task_kill_result_t during;bool applied=request_when(r,TASK_TEST_MATCH_EXITING,&during,5000)==TASK_TEST_REQUEST_APPLIED;kt_store_u8(&r->cleanup_release,1);bool done=finish_case(r,killed?TASK_EXIT_KILLED:TASK_EXIT_NORMAL);
#ifdef HOBBYOS_KILL_NEGATIVE_ACCEPT_EXITING
if(!killed&&applied&&during==TASK_KILL_ACCEPTED&&done){serial_write_all("[KILLTEST][NEGATIVE] EXITING_ACCEPTED_NORMAL_DETECTED\n");return 0;}
#endif
return emit(killed?"EXITING_KILLED":"EXITING_NORMAL",applied&&during==TASK_KILL_ALREADY_EXITING&&(!killed||first==TASK_KILL_ACCEPTED)&&done);}
static int test_parser(void){task_id_t id=0;bool ok=task_id_parse_decimal_ex("1",&id)==TASK_ID_PARSE_OK&&id==1&&task_id_parse_decimal_ex("0",&id)==TASK_ID_PARSE_ZERO&&id==0&&task_id_parse_decimal_ex("",&id)==TASK_ID_PARSE_EMPTY&&task_id_parse_decimal_ex("-1",&id)==TASK_ID_PARSE_SIGN&&task_id_parse_decimal_ex("+1",&id)==TASK_ID_PARSE_SIGN&&task_id_parse_decimal_ex("12x",&id)==TASK_ID_PARSE_NON_DECIMAL&&task_id_parse_decimal_ex("18446744073709551616",&id)==TASK_ID_PARSE_OVERFLOW&&task_id_parse_decimal_ex("18446744073709551615",&id)==TASK_ID_PARSE_OK&&id==UINT64_MAX&&task_id_parse_decimal("0",&id)&&id==0&&!strcmp(scheduler_task_kill_result_to_string(TASK_KILL_ALREADY_EXITING),"ALREADY_EXITING")&&!strcmp(scheduler_task_kill_result_to_string(TASK_KILL_ERR_NOT_FOUND),"NOT_FOUND");return emit("PARSER",ok);}
static int test_timeout_race(uint32_t rounds){scheduler_test_set_lifecycle_log_quiet(true);uint64_t normal=0,killed=0,accepted_normal=0,not_found=0,stuck_before=kt_load_u64(&g_worker_timeouts);for(uint32_t i=0;i<rounds;i++){killtest_result_t*r=create_case(KW_TIMEOUT,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(!r)return emit("TIMEOUT_RACE",false);uint32_t bucket=i&3u;if(bucket==1)timer_sleep(1);else if(bucket==2)timer_sleep(3);else if(bucket==3)timer_sleep(6);task_kill_result_t kr=scheduler_request_kill(r->task_id);bool seen=wait_u8(&r->cleanup_seen,5000);task_exit_reason_t reason=seen?r->exit_reason:TASK_EXIT_NONE;if(kr==TASK_KILL_ERR_NOT_FOUND)not_found++;if(kr==TASK_KILL_ACCEPTED&&reason==TASK_EXIT_NORMAL){accepted_normal++;kt_inc_u64(&g_accepted_normal);}if(reason==TASK_EXIT_KILLED)killed++;else if(reason==TASK_EXIT_NORMAL)normal++;if(!finish_case(r,reason)&&seen)break;}uint64_t stuck=kt_load_u64(&g_worker_timeouts)-stuck_before;bool ok=normal+killed==rounds&&normal>0&&killed>0&&!accepted_normal&&!stuck&&!not_found;serial_write_all("[KILLTEST][TIMEOUT_RACE] ");serial_write_all(ok?"PASS":"FAIL");serial_write_all(" rounds=");print_u64(rounds);serial_write_all(" normal=");print_u64(normal);serial_write_all(" killed=");print_u64(killed);serial_write_all(" accepted_normal=");print_u64(accepted_normal);serial_write_all(" stuck=");print_u64(stuck);serial_write_all(" not_found=");print_u64(not_found);serial_write_all("\n");scheduler_test_set_lifecycle_log_quiet(false);return ok?0:1;}
static int ui_setup(void){if(g_ui_no)return emit("UI_SETUP",false);task_snapshot_t *s=g_kt_page;task_snapshot_result_t n=scheduler_snapshot_tasks(s,32,0);for(uint32_t i=0;i<n.written;i++)if(s[i].is_idle){g_ui_prot=s[i].id;break;}g_ui_no=create_case(KW_NONKILL,TASK_FLAG_SYSTEM,0,NULL);g_ui_free=create_case(KW_GATED,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);g_ui_pend=create_case(KW_GATED,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(g_ui_pend)scheduler_request_kill(g_ui_pend->task_id);g_ui_exit=create_case(KW_NORMAL,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,1,NULL);g_ui_zomb=create_case(KW_GATED,TASK_FLAG_SYSTEM|TASK_FLAG_KILLABLE,0,NULL);if(g_ui_zomb)kt_store_u8(&g_ui_zomb->release,1);bool ok=g_ui_prot&&g_ui_no&&g_ui_free&&g_ui_pend&&g_ui_exit&&g_ui_zomb&&wait_u8(&g_ui_exit->cleanup_entered,5000)&&wait_state(g_ui_zomb->task_id,TASK_ZOMBIE,NULL,5000);serial_write_all("[KILLTEST][UI_SETUP] ");serial_write_all(ok?"PASS":"FAIL");serial_write_all(" prot=");print_u64(g_ui_prot);serial_write_all(" no=");print_u64(g_ui_no?g_ui_no->task_id:0);serial_write_all(" killable=");print_u64(g_ui_free?g_ui_free->task_id:0);serial_write_all(" pend=");print_u64(g_ui_pend?g_ui_pend->task_id:0);serial_write_all(" exit=");print_u64(g_ui_exit?g_ui_exit->task_id:0);serial_write_all(" zomb=");print_u64(g_ui_zomb?g_ui_zomb->task_id:0);serial_write_all("\n");return ok?0:1;}
static int ui_status(void){task_snapshot_t a,b,c,d,e,f;bool ready=g_ui_prot&&g_ui_no&&g_ui_free&&g_ui_pend&&g_ui_exit&&g_ui_zomb;bool ok=ready&&snapshot_id(g_ui_prot,&a)&&snapshot_id(g_ui_no->task_id,&b)&&snapshot_id(g_ui_free->task_id,&c)&&snapshot_id(g_ui_pend->task_id,&d)&&snapshot_id(g_ui_exit->task_id,&e)&&snapshot_id(g_ui_zomb->task_id,&f);ok=ok&&!strcmp(scheduler_task_kill_state_to_string(&a),"PROT")&&!strcmp(scheduler_task_kill_state_to_string(&b),"NO")&&!strcmp(scheduler_task_kill_state_to_string(&c),"-")&&!strcmp(scheduler_task_kill_state_to_string(&d),"PEND")&&!strcmp(scheduler_task_kill_state_to_string(&e),"EXIT")&&!strcmp(scheduler_task_kill_state_to_string(&f),"ZOMB");serial_write_all(ok?"[KILLTEST][UI_STATUS] PASS PROT=1 NO=1 FREE=1 PEND=1 EXIT=1 ZOMB=1\n":"[KILLTEST][UI_STATUS] FAIL\n");return ok?0:1;}
static int ui_cleanup(void){if(!g_ui_no)return emit("UI_CLEANUP",false);task_snapshot_t free_snapshot;bool free_killed=snapshot_id(g_ui_free->task_id,&free_snapshot)&&free_snapshot.kill_pending;kt_store_u8(&g_ui_no->release,1);kt_store_u8(&g_ui_free->release,1);kt_store_u8(&g_ui_pend->release,1);kt_store_u8(&g_ui_exit->cleanup_release,1);bool ok=finish_case(g_ui_no,TASK_EXIT_NORMAL)&finish_case(g_ui_free,free_killed?TASK_EXIT_KILLED:TASK_EXIT_NORMAL)&finish_case(g_ui_pend,TASK_EXIT_KILLED)&finish_case(g_ui_exit,TASK_EXIT_NORMAL)&finish_case(g_ui_zomb,TASK_EXIT_NORMAL);g_ui_no=g_ui_free=g_ui_pend=g_ui_exit=g_ui_zomb=NULL;g_ui_prot=0;ok=ok&&!kt_load_u64(&g_contexts_live)&&!kt_load_u64(&g_quarantined_contexts)&&!scheduler_test_reap_holds();serial_write_all(ok?"[KILLTEST][UI_CLEANUP] PASS contexts=0 quarantine=0 holds=0\n":"[KILLTEST][UI_CLEANUP] FAIL\n");return ok?0:1;}
static bool has_prefix(const char*s,const char*p){while(*p)if(*s++!=*p++)return false;return true;}
static int test_smpstress_sweep(void){task_id_t *ids=g_kt_ids;uint32_t n=0,off=0;for(;;){task_snapshot_t *s=g_kt_page;task_snapshot_result_t r=scheduler_snapshot_tasks(s,32,off);for(uint32_t i=0;i<r.written&&n<32;i++)if(has_prefix(s[i].name,"smpstress-")&&(s[i].flags&TASK_FLAG_KILLABLE))ids[n++]=s[i].id;off+=r.written;if(!r.truncated||!r.written)break;}task_kill_stats_t a,b;scheduler_kill_stats_snapshot(&a);uint32_t accepted=0,reaped=0;for(uint32_t i=0;i<n;i++){task_kill_result_t k=scheduler_request_kill(ids[i]);if(k==TASK_KILL_ACCEPTED||k==TASK_KILL_ALREADY_PENDING)accepted++;if(i<2)(void)scheduler_request_kill(ids[i]);}for(uint32_t i=0;i<n;i++)if(wait_gone(ids[i],10000))reaped++;scheduler_kill_stats_snapshot(&b);uint64_t killed=b.exits_killed-a.exits_killed,cleaned=b.cleanup_callbacks_invoked-a.cleanup_callbacks_invoked;bool ok=n>0&&accepted==n&&killed==n&&cleaned==n&&reaped==n;serial_write_all("[SMP][KILL_SWEEP] ");serial_write_all(ok?"PASS":"FAIL");serial_write_all(" workers=");print_u64(n);serial_write_all(" killed=");print_u64(killed);serial_write_all(" cleaned=");print_u64(cleaned);serial_write_all(" reaped=");print_u64(reaped);serial_write_all("\n");return ok?0:1;}
static int stats(void){task_kill_stats_t s;scheduler_kill_stats_snapshot(&s);serial_write_all("[KILLTEST][STATS] requests=");print_u64(s.requests);serial_write_all(" accepted=");print_u64(s.accepted);serial_write_all(" exiting=");print_u64(s.already_exiting);serial_write_all(" normal=");print_u64(s.exits_normal);serial_write_all(" killed=");print_u64(s.exits_killed);serial_write_all(" cleanup_started=");print_u64(s.cleanup_started);serial_write_all(" cleanup_done=");print_u64(s.cleanup_completed);serial_write_all(" callbacks=");print_u64(s.cleanup_callbacks_invoked);serial_write_all(" contexts=");print_u64(g_contexts_live);serial_write_all(" holds=");print_u64(scheduler_test_reap_holds());serial_write_all("\n");return 0;}
static int check(void){task_kill_stats_t s;scheduler_runtime_stats_t sched;scheduler_kill_stats_snapshot(&s);bool sched_ok=scheduler_validate_runtime_invariants(&sched);uint64_t pending=0;bool scan_ok=scan_pending_all(clock_monotonic_ns(),&pending);bool order=s.exit_phases_completed<=s.exit_phases_started&&s.cleanup_completed<=s.cleanup_started&&s.cleanup_callbacks_invoked<=s.cleanup_completed;uint64_t missing=order?s.exit_phases_started-s.exit_phases_completed:UINT64_MAX;uint64_t cleanup_missing=order?s.cleanup_started-s.cleanup_completed:UINT64_MAX;bool counters=s.cancellation_points==s.exits_killed;uint64_t contexts=kt_load_u64(&g_contexts_live),quarantine=kt_load_u64(&g_quarantined_contexts),wrong=kt_load_u64(&g_wrong_reason),accepted_normal=kt_load_u64(&g_accepted_normal),timeouts=kt_load_u64(&g_worker_timeouts);bool ok=sched_ok&&scan_ok&&order&&counters&&!pending&&!missing&&!cleanup_missing&&!s.cleanup_duplicate_attempts&&!s.exit_duplicate_attempts&&!wrong&&!accepted_normal&&!contexts&&!quarantine&&!scheduler_test_reap_holds()&&!timeouts;serial_write_all("[KILLTEST][CHECK] ");serial_write_all(ok?"PASS":"FAIL");serial_write_all(" pending=");print_u64(pending);serial_write_all(" cleanup_missing=");print_u64(cleanup_missing);serial_write_all(" duplicate=");print_u64(s.cleanup_duplicate_attempts+s.exit_duplicate_attempts);serial_write_all(" wrong_reason=");print_u64(wrong);serial_write_all(" accepted_normal=");print_u64(accepted_normal);serial_write_all(" contexts=");print_u64(contexts);serial_write_all(" quarantine=");print_u64(quarantine);serial_write_all(" holds=");print_u64(scheduler_test_reap_holds());serial_write_all("\n");return ok?0:1;}
static int all(void){int r=0;r|=test_ready();r|=test_running();r|=test_wait(KW_SLEEPING,TASK_TEST_MATCH_SLEEPING_WAIT,"SLEEPING");r|=test_wait(KW_BLOCKED,TASK_TEST_MATCH_BLOCKED_WAIT,"BLOCKED");r|=test_duplicate();r|=test_protected();r|=test_nonkill();r|=test_rename();r|=test_normal();r|=test_zombie();r|=test_exiting(false);r|=test_exiting(true);r|=test_parser();r|=check();serial_write_all(r?"[KILLTEST][ALL] FAIL\n":"[KILLTEST][ALL] PASS\n");return r;}
static uint32_t parse_rounds(int argc,char**argv){task_id_t n;if(argc>2&&task_id_parse_decimal(argv[2],&n)&&n&&n<=100000)return(uint32_t)n;return 500;}
static int ui_cli_repro(uint32_t iterations){uint32_t done=0;for(;done<iterations;done++){if(ui_setup()||ui_status()||test_parser()||ui_cleanup()||check())break;}bool ok=done==iterations&&!kt_load_u64(&g_contexts_live)&&!scheduler_test_reap_holds();serial_write_all("[KILLTEST][UI_CLI_REPRO] ");serial_write_all(ok?"PASS":"FAIL");serial_write_all(" iterations=");print_u64(done);serial_write_all(" faults=");print_u64(ok?0:1);serial_write_all(" contexts=");print_u64(kt_load_u64(&g_contexts_live));serial_write_all(" holds=");print_u64(scheduler_test_reap_holds());serial_write_all("\n");return ok?0:1;}
int cmd_killtest(int argc,char**argv){const char*s=argc>1?argv[1]:"check";if(!strcmp(s,"cli-telemetry")||!strcmp(s,"clitelemetry")){bool on=argc>2&&!strcmp(argv[2],"on");kt_store_u8(&g_cli_telemetry,on);serial_write_all(on?"[KILLTEST][CLI_TELEMETRY] ON\n":"[KILLTEST][CLI_TELEMETRY] OFF\n");return 0;}if(!strcmp(s,"ui-telemetry")||!strcmp(s,"uitelemetry")){bool on=argc>2&&!strcmp(argv[2],"on");kt_store_u8(&g_ui_telemetry,on);serial_write_all(on?"[KILLTEST][UI_TELEMETRY] ON\n":"[KILLTEST][UI_TELEMETRY] OFF\n");return 0;}if(!strcmp(s,"ready"))return test_ready();if(!strcmp(s,"running"))return test_running();if(!strcmp(s,"sleeping"))return test_wait(KW_SLEEPING,TASK_TEST_MATCH_SLEEPING_WAIT,"SLEEPING");if(!strcmp(s,"blocked"))return test_wait(KW_BLOCKED,TASK_TEST_MATCH_BLOCKED_WAIT,"BLOCKED");if(!strcmp(s,"duplicate"))return test_duplicate();if(!strcmp(s,"protected"))return test_protected();if(!strcmp(s,"nonkillable"))return test_nonkill();if(!strcmp(s,"rename"))return test_rename();if(!strcmp(s,"cleanup"))return test_running()|test_wait(KW_SLEEPING,TASK_TEST_MATCH_SLEEPING_WAIT,"CLEANUP_SLEEP")|test_wait(KW_BLOCKED,TASK_TEST_MATCH_BLOCKED_WAIT,"CLEANUP_BLOCK");if(!strcmp(s,"normal"))return test_normal();if(!strcmp(s,"zombie"))return test_zombie();if(!strcmp(s,"exiting-normal")||!strcmp(s,"exitingnormal"))return test_exiting(false);if(!strcmp(s,"exiting-killed")||!strcmp(s,"exitingkilled"))return test_exiting(true);if(!strcmp(s,"timeout-race")||!strcmp(s,"timeoutrace"))return test_timeout_race(parse_rounds(argc,argv));if(!strcmp(s,"parser"))return test_parser();if(!strcmp(s,"ui-setup")||!strcmp(s,"uisetup"))return ui_setup();if(!strcmp(s,"ui-status")||!strcmp(s,"uistatus"))return ui_status();if(!strcmp(s,"ui-cleanup")||!strcmp(s,"uicleanup"))return ui_cleanup();if(!strcmp(s,"ui-cli-repro")||!strcmp(s,"uiclirepro"))return ui_cli_repro(parse_rounds(argc,argv));if(!strcmp(s,"smpstress-sweep")||!strcmp(s,"smpstresssweep"))return test_smpstress_sweep();if(!strcmp(s,"stats"))return stats();if(!strcmp(s,"check"))return check();if(!strcmp(s,"all"))return all();return emit("UNKNOWN",false);}
