#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd); cd "$root"
serial=.qemu/qemu-serial.log;hmp=(python3 scripts/qemu_hmp.py --socket .qemu/hmp.sock);mkdir -p artifacts/build
harness_start_line=0;harness_command=boot
source scripts/harness-common.sh
harness_lock
cleanup(){ scripts/qemu-agent.sh stop >/dev/null 2>&1 || true; };trap cleanup EXIT
count(){ grep -F -c -- "$1" "$serial" 2>/dev/null || true; }
diagnose(){ local command=$1 pass=$2 failure=${3:-timeout};echo "CL08 command: $command" >&2;echo "expected: $pass" >&2;echo "failure: $failure" >&2;tail -100 "$serial" >&2 || true;scripts/qemu-agent.sh status >&2 || true; }
send_expect(){ local command=$1 pass=$2 timeout=${3:-180};shift 3 || true;local start_lines deadline line failure="";start_lines=$(wc -l <"$serial" 2>/dev/null || echo 0);deadline=$((SECONDS+timeout));hmp_text "$command" normal --enter >/dev/null
 while ((SECONDS<=deadline));do
  if ! pgrep -f 'qemu-system-x86_64' >/dev/null;then diagnose "$command" "$pass" "QEMU exited";return 1;fi
  line=$(tail -n +$((start_lines+1)) "$serial" 2>/dev/null || true)
  if grep -Fq -- "$pass" <<<"$line";then return 0;fi
  failure=$(grep -m1 -E '\[REAPTEST\].*FAIL|\[REAPER\]\[STRUCTURAL_FAULT\]|PANIC|#PF|#GP|FATAL' <<<"$line" || true)
  if [[ -n $failure ]];then diagnose "$command" "$pass" "$failure";return 1;fi
  for failure in "$@";do if [[ -n $failure ]]&&grep -Fq -- "$failure" <<<"$line";then diagnose "$command" "$pass" "$failure";return 1;fi;done
  sleep 1
 done
 diagnose "$command" "$pass" timeout;return 1
}
send(){ send_complete "$@"; }
wait_occurrences(){ local pattern=$1 wanted=$2 timeout=${3:-30};local deadline=$((SECONDS+timeout));while ((SECONDS<=deadline));do local found;found=$(count "$pattern");((found>=wanted))&&return 0;grep -Eq '\[REAPTEST\].*FAIL|PANIC|#PF|#GP|FATAL' "$serial"&&return 1;sleep 1;done;return 1; }
start(){ start_qemu "$1" "${2:-tcg}"; }
clean_log(){ ! grep -E 'FAIL|PANIC|#PF|#GP|FATAL' "$1"; }
positive(){ for n in 1 2 4 8;do start "$n" tcg;send "accounttest reaper-quiescence 32" "[ACCOUNT][REAPER_QUIESCENCE] PASS workers=32 gone=32" 90;send "reaptest snapshot-boundary 100" "[REAPTEST][SNAPSHOT_BOUNDARY_LOOP] PASS rounds=100 verified=100 failures=0" 180;send "accounttest clock-classifier" "[ACCOUNT][CLOCK_CLASSIFIER] PASS" 60;send "reaptest fixture" "[REAPTEST][FIXTURE] PASS completed=1 reaped=1" 60;send "reaptest priority" "[REAPTEST][PRIORITY] PASS" 60;send "reaptest check" "[REAPTEST][CHECK] PASS" 60;send "reaptest all" "[REAPTEST][CHECK] PASS" 360;if ((n==1));then send "reaptest normal 1000" "[REAPTEST][NORMAL] PASS created=1000" 180;send "reaptest killed 1000" "[REAPTEST][KILLED] PASS created=1000" 180;send "reaptest concurrent-churn 100 100 100" "[REAPTEST][CONCURRENT_CHURN] PASS" 360;elif ((n==2));then send "reaptest concurrent-churn 250 250 250" "[REAPTEST][CONCURRENT_CHURN] PASS" 360;else send "reaptest concurrent-churn 1000 1000 1000" "[REAPTEST][CONCURRENT_CHURN] PASS" 600;fi;if [[ $n == 8 ]];then send "reaptest create-handle-race 100000" "[REAPTEST][CREATE_HANDLE_RACE] PASS" 900;send "accounttest clock-smp 32 1000000" "[ACCOUNT][CLOCK_SMP] PASS" 600;fi;send "killtest check" "[KILLTEST][CHECK] PASS" 60;send "schedtest check" "[SCHED][CHECK] PASS" 60;send "synctest check" "[SYNC][CHECK] PASS" 60;send "accounttest check" "[ACCOUNT][CHECK] PASS" 60;cp "$serial" "artifacts/build/cl08fix6-smp${n}.log";clean_log "artifacts/build/cl08fix6-smp${n}.log";cleanup;done; }
zombie_mem(){ start 4 tcg;send "reaptest zombie-mem setup" "[REAPTEST][ZOMBIE_MEM_SETUP] PASS" 60;send ps "[PS][ZOMBIE_MEM]" 30;local before ended;before=$(count "[TASKMAN][ZOMBIE_MEM]");ended=$(count "[MODAL] session_end OK");hmp_text taskman normal --enter >/dev/null;wait_occurrences "[TASKMAN][ZOMBIE_MEM]" $((before+2)) 30;hmp_key esc normal >/dev/null;wait_occurrences "[MODAL] session_end OK" $((ended+1)) 30;send "reaptest zombie-mem cleanup" "[REAPTEST][ZOMBIE_MEM] PASS" 60;cp "$serial" artifacts/build/cl08fix6-zombie-mem.log;clean_log artifacts/build/cl08fix6-zombie-mem.log;cleanup; }
negative_one(){ local macro=$1 cmd=$2 sentinel=$3 log=$4 rc=0;make kernel-check JOBS=2 KERNEL_EXTRA_CFLAGS="-D$macro" >/dev/null;make image KERNEL_EXTRA_CFLAGS="-D$macro" >/dev/null;start 2 tcg;send "$cmd" "$sentinel" 90||rc=$?;cp "$serial" "artifacts/build/$log";cleanup;make kernel-check JOBS=2 >/dev/null;make image >/dev/null;return "$rc"; }
negatives(){ negative_one HOBBYOS_REAPER_NEGATIVE_AGE_ONLY "reaptest negative-age" "[REAPTEST][NEGATIVE] AGE_ONLY_REAPER_DETECTED" cl08fix6-negative-age.log;negative_one HOBBYOS_REAPER_NEGATIVE_IGNORE_TIMER_REF "reaptest timer-ref" "[REAPTEST][NEGATIVE] TIMER_REF_IGNORED_DETECTED" cl08fix6-negative-timer-ref.log;negative_one HOBBYOS_REAPTEST_NEGATIVE_LATE_TIMER_HOLD "reaptest timer-ref-late-negative" "[REAPTEST][NEGATIVE] LATE_TIMER_HOLD_DETECTED" cl11fix6-negative-late-timer-hold.log;negative_one HOBBYOS_REAPER_NEGATIVE_DUPLICATE_NOTIFICATION "reaptest negative" "[REAPTEST][NEGATIVE] DUPLICATE_NOTIFICATION_DETECTED" cl08fix6-negative-notify.log;negative_one HOBBYOS_REAPER_NEGATIVE_ON_CPU "reaptest oncpu" "[REAPTEST][NEGATIVE] ON_CPU_REAP_DETECTED" cl08fix6-negative-oncpu.log; }
clock_smp_quiescence(){ start 8 tcg;for run in 1 2 3;do send "reaptest concurrent-churn 1000 1000 1000" "[REAPTEST][CONCURRENT_CHURN] PASS" 600;send "reaptest create-handle-race 100000" "[REAPTEST][CREATE_HANDLE_RACE] PASS" 900;send "accounttest clock-smp 32 1000000" "[ACCOUNT][CLOCK_SMP] PASS" 600;grep -F '[ACCOUNT][CLOCK_SMP] PASS' "$serial"|tail -1|grep -F 'worker_handles_gone=32'|grep -F 'free_inflight=0' >/dev/null;cp "$serial" "artifacts/build/cl11fix4-clock-smp-run${run}.log";done;echo "[CL08][CLOCK_SMP_QUIESCENCE] PASS runs=3"|tee -a "$serial";cleanup; }
boundary_smp1(){ for boot in 1 2 3;do start 1 tcg;send "reaptest snapshot-boundary 100" "[REAPTEST][SNAPSHOT_BOUNDARY_LOOP] PASS rounds=100 verified=100 failures=0" 180;send "reaptest concurrent-churn 100 100 100" "[REAPTEST][CONCURRENT_CHURN] PASS" 360;cp "$serial" "artifacts/build/cl11fix5-boundary-smp1-boot${boot}.log";cleanup;done; }
boundary_and_quiescence(){ start 8 tcg;for run in 1 2 3 4 5;do send "reaptest snapshot-boundary 100" "[REAPTEST][SNAPSHOT_BOUNDARY_LOOP] PASS rounds=100 verified=100 failures=0" 180;send "reaptest concurrent-churn 1000 1000 1000" "[REAPTEST][CONCURRENT_CHURN] PASS" 600;send "reaptest create-handle-race 100000" "[REAPTEST][CREATE_HANDLE_RACE] PASS" 900;send "accounttest clock-smp 32 1000000" "[ACCOUNT][CLOCK_SMP] PASS" 600;grep -F '[REAPTEST][CONCURRENT_CHURN] PASS' "$serial"|tail -1|grep -F 'forced_generation_changes=1'|grep -F 'children_gone=2000' >/dev/null;grep -F '[ACCOUNT][CLOCK_SMP] PASS' "$serial"|tail -1|grep -F 'worker_handles_gone=32'|grep -F 'free_inflight=0' >/dev/null;cp "$serial" "artifacts/build/cl11fix5-cl08-run${run}.log";done;echo "[CL08][BOUNDARY_AND_QUIESCENCE] PASS runs=5"|tee -a "$serial";cleanup; }
timer_ref_loops(){ for smp in 1 8;do for boot in 1 2 3;do start "$smp" tcg;send "reaptest timer-ref-loop 1000" "[REAPTEST][TIMER_REF_LOOP] PASS count=1000" 600;cp "$serial" "artifacts/build/cl11fix6-timer-ref-smp${smp}-boot${boot}.log";cleanup;done;done; }
timer_ref_deterministic(){ start 8 tcg;for run in 1 2 3 4 5;do send "reaptest snapshot-boundary 100" "[REAPTEST][SNAPSHOT_BOUNDARY_LOOP] PASS" 180;send "reaptest concurrent-churn 1000 1000 1000" "[REAPTEST][CONCURRENT_CHURN] PASS" 600;send "reaptest create-handle-race 100000" "[REAPTEST][CREATE_HANDLE_RACE] PASS" 900;send "accounttest clock-smp 32 1000000" "[ACCOUNT][CLOCK_SMP] PASS" 600;send "reaptest timer-ref-loop 100" "[REAPTEST][TIMER_REF_LOOP] PASS count=100" 180;cp "$serial" "artifacts/build/cl11fix6-heavy-run${run}.log";done;echo "[CL08][TIMER_REF_DETERMINISTIC] PASS runs=5"|tee -a "$serial";cleanup; }
soak(){ local duration=${DURATION_MS:-180000};((duration>=180000));start 8 tcg;local begin=$(( $(date +%s%N)/1000000 )) cycles=0;while (( $(date +%s%N)/1000000-begin<duration ));do send "reaptest concurrent-churn 1000 1000 1000" "[REAPTEST][CONCURRENT_CHURN] PASS" 600;send "reaptest timer-ref" "[REAPTEST][TIMER_REF] PASS" 90;send "reaptest snapshot" "[REAPTEST][SNAPSHOT] PASS" 120;cycles=$((cycles+1));done;for _ in $(seq 1 10);do modal_cycle_complete;done;send "reaptest check" "[REAPTEST][CHECK] PASS" 60;send "reaptest create-handle-race 100000" "[REAPTEST][CREATE_HANDLE_RACE] PASS" 900;send "accounttest clock-smp 32 1000000" "[ACCOUNT][CLOCK_SMP] PASS" 600;send "killtest check" "[KILLTEST][CHECK] PASS" 60;send "schedtest check" "[SCHED][CHECK] PASS" 60;send "synctest check" "[SYNC][CHECK] PASS" 60;send "accounttest check" "[ACCOUNT][CHECK] PASS" 60;cp "$serial" artifacts/build/cl08fix6-soak-smp8.log;clean_log artifacts/build/cl08fix6-soak-smp8.log;echo "[REAPTEST][SOAK] PASS cycles=$cycles duration_ms=$duration" >>artifacts/build/cl08fix6-soak-smp8.log;cleanup; }
source scripts/harness-common.sh
case ${1:-all} in positive)positive;;clock-smp-quiescence)clock_smp_quiescence;;boundary-smp1)boundary_smp1;;boundary-and-quiescence)boundary_and_quiescence;;timer-ref-loops)timer_ref_loops;;timer-ref-deterministic)timer_ref_deterministic;;zombie-mem)zombie_mem;;negatives)negatives;;soak)soak;;all)timer_ref_loops;boundary_smp1;positive;timer_ref_deterministic;zombie_mem;negatives;soak;;*)exit 2;;esac
